"""Filled JARL Toyama branch sheets, generated by the application's Qt runtime."""
from pathlib import Path
from math import ceil
from PySide6.QtCore import QBuffer,QByteArray,QIODevice,QRectF,QSize,Qt,QMarginsF
from PySide6.QtGui import QPdfWriter,QPageSize,QPageLayout,QPainter,QFont,QFontDatabase,QFontMetricsF,QColor,QPen
from PySide6.QtPdf import QPdfDocument

BANDS=['21','24','28','50','144','430','1200','2400']

def render(selection,rule,draft,result,info,context):
    from contest_export import clean,key,OATH
    from contest import entries
    from contest_rules import score
    from copy import deepcopy
    for k in ('name','address','signature','date','opplace'):
        clean(info.get(k,''),k,True)
    if info.get('oath') is not True:raise ValueError('宣誓を確認してください。')
    from contest_station import check_submission
    check_submission(rule,context,info,selection.rows[0][0])
    if info.get('zone','JST')!='JST':raise ValueError('富山のログ時刻はJSTです。')
    if info.get('contest')!=rule['event']['submission']['contest']:raise ValueError('大会名が異なります。')
    c=next(x for x in rule['event']['categories'] if x['id']==context['category'])
    if info.get('category')!=c.get('submission_code',c['id']):raise ValueError('部門が異なります。')
    if str(info.get('power'))!=str(context.get('power')):raise ValueError('提出出力と参加条件が異なります。')
    if c.get('operator')=='MO' and (not info.get('multiop') or not info.get('multioplist','').strip()):raise ValueError('MOは全運用者を入力してください。')
    if c.get('operator')=='SO' and info.get('multiop'):raise ValueError('SO部門と運用者設定が異なります。')
    values=entries(selection,draft)
    from contest_normalization import working_values
    for v in values:v['band'],v['mode']=working_values(rule['event'],v['band'],v['mode'],v.get('contest_band',''))
    d=context['declarations'];single=len(c['bands'])==1
    all_result=result
    if single:
        rc=deepcopy(rule);cc=next(x for x in rc['event']['categories'] if x['id']==c['id']);cc['bands']=[b for b in BANDS if b!='24'];cc['max_bands']=7
        all_result=score(rc,values,context)
        if all_result.problems:raise ValueError('他帯域の資料も確認してください: '+ ' / '.join(all_result.problems[:3]))
    families=set(QFontDatabase.families())
    candidates=('Yu Gothic','Yu Gothic UI','Meiryo','Meiryo UI','MS Gothic','MS UI Gothic','BIZ UDPGothic','Noto Sans JP','Noto Sans CJK JP')
    font_family=next((f for f in candidates if f in families),None)
    if font_family is None and __import__('os').name=='nt':
        # Qt's offscreen Windows platform can omit installed system fonts from
        # QFontDatabase.families().  Load a known Japanese Windows font file
        # explicitly before declaring the machine unsupported.
        win=Path(__import__('os').environ.get('WINDIR',r'C:\Windows'))/'Fonts'
        for filename in ('YuGothM.ttc','YuGothR.ttc','meiryo.ttc','msgothic.ttc'):
            fp=win/filename
            if not fp.exists():continue
            font_id=QFontDatabase.addApplicationFont(str(fp))
            if font_id>=0:
                loaded=QFontDatabase.applicationFontFamilies(font_id)
                if loaded:
                    font_family=loaded[0];break
    if font_family is None:raise ValueError('日本語PDF用フォント（メイリオ/游ゴシック/Noto Sans JP等）が必要です。')
    data=QByteArray();buffer=QBuffer(data);buffer.open(QIODevice.WriteOnly);writer=QPdfWriter(buffer);writer.setPageSize(QPageSize(QPageSize.A4));writer.setResolution(72);writer.setPageMargins(QMarginsF(0,0,0,0),QPageLayout.Point);writer.setTitle('富山県非常無線通信訓練コンテスト 提出用');p=QPainter(writer);pages=0
    root=Path(__file__).parent/'config/templates/pdf';templates={}
    try:
        for name in ('OSOSUMMARY','QSOLOG'):
            doc=QPdfDocument();err=doc.load(str(root/('toyama_'+name+'.pdf')))
            if err!=QPdfDocument.Error.None_:raise ValueError('支部様式を読み込めません: '+name)
            templates[name]=doc.render(0,QSize(1786,2526));doc.close()
        def page(name=None):
            nonlocal pages
            if pages:writer.newPage()
            pages+=1;p.setPen(Qt.black)
            if name:p.drawImage(QRectF(0,0,595.32,841.92),templates[name])
        def cell(x,y,w,h,text,size=9,cover=False):
            text=str(text) if text is not None else ''
            if cover:p.fillRect(QRectF(x,y,w,h),QColor('#cfffff'))
            size=float(size)
            while size>=5:
                font=QFont(font_family);font.setPointSizeF(size);p.setFont(font);fm=QFontMetricsF(font,p.device());rect=fm.boundingRect(QRectF(0,0,w-4,1000),Qt.TextWordWrap,text)
                if rect.height()<=h-2 and max((fm.horizontalAdvance(ch) for ch in text),default=0)<=w-4:break
                size-=0.5
            else:raise ValueError('指定用紙の欄に収まりません。省略せず提出情報を確認してください: '+text[:45])
            p.drawText(QRectF(x+2,y+1,w-4,h-2),Qt.TextWordWrap|Qt.AlignVCenter,text)
        def summary(res,reference=False):
            page('OSOSUMMARY');cell(346,88,18,17,'49',10);cell(366,123,161,17,('参考 全運用帯域' if reference else c['name']),8);cell(367,176,160,15,selection.rows[0][0],12)
            for j,b in enumerate(BANDS):
                ix=[i for i,v in enumerate(values) if v['band']==b];y=88+j*17.4
                if b=='24':continue
                pts=sum(res.rows[i]['points'] or 0 for i in ix);multi=len({res.rows[i]['multi'] for i in ix if res.rows[i]['multi'] is not None})
                cell(145,y,55,16,len(ix) if ix else '');cell(201,y,65,16,pts if ix else '');cell(291,y,45,16,multi if ix else '')
            for x,w,v in [(145,54,len(values)),(202,64,res.points),(291,45,res.multi1),(368,158,res.total)]:cell(x,242,w,25,v,12,True)
            if single and not reference:p.setPen(QPen(QColor('red'),1.5));p.drawRect(QRectF(54,88+BANDS.index(c['bands'][0])*17.4,284,17));p.setPen(Qt.black)
            fields=[(294,12,d.get('postcode','')),(309,12,info['address']),(324,11,info.get('tel','')),(338,20,info['name']),(361,20,info.get('clubname','')),(384,12,info.get('email','')),(399,11,info.get('licenseclass','')),(413,12,d['equipment']),(428,11,d['antenna']),(443,11,str(context['power'])+' W'),(457,11,info['opplace']),(471,11,info.get('opcall','')),(486,11,info.get('multioplist','')),(500,17,info.get('clubnumber','')),(521,16,info.get('clubname','')),(540,34,info.get('comments','')+(' / 参考資料: 全運用帯域の集計。参加帯は主サマリー赤枠。' if reference else '')),(613,20,info['date']),(636,20,info['signature']),(659,19,info.get('callsign') or selection.rows[0][0])]
            for y,h,t in fields:cell(145,y,381,h,t,8)
        summary(result)
        if single:summary(all_result,True)
        for b in BANDS:
            ix=sorted([i for i,v in enumerate(values) if v['band']==b],key=lambda i:(values[i]['date'],values[i]['time'],i))
            if not ix:continue
            seen_multi=set()
            for start in range(0,len(ix),50):
                part=ix[start:start+50];page('QSOLOG');cell(295,22,68,23,rule['year']);cell(146,47,80,20,selection.rows[0][0],9);cell(295,47,68,20,b,10);cell(486,47,30,20,start//50+1)
                new_multis=0
                for n,i in enumerate(part):
                    v=values[i];s=all_result.rows[i];y=99.6+n*13.92
                    token=s.get('multi');show=v.get('area','') if token is not None and token not in seen_multi else '-';new_multis+=show!='-';seen_multi.add(token)
                    texts=[(70,74,v['date'][5:]+' '+v['time']),(146,80,v['call']),(229,64,v['rst_sent']+' '+v['sent']),(295,68,v['rst_received']+' '+v['exchange']),(365,50,show),(417,30,s['points']),(450,34,v.get('operator_name','')),(486,31,v['mode'])]
                    for x,w,t in texts:cell(x,y,w,13.8,t,7)
                cell(146,796,80,22,len(part));cell(365,796,49,22,new_multis);cell(417,796,30,22,sum(all_result.rows[i]['points'] for i in part))
            if len(ix)>50:
                ordered=sorted(ix,key=lambda i:(__import__('re').split('[0-9]',values[i]['call'].split('/')[0])[-1],values[i]['call'],values[i]['date'],values[i]['time']))
                for start in range(0,len(ordered),44):
                    page();cell(45,35,510,25,f'重複チェック表 {b} MHz / '+selection.rows[0][0],13)
                    cell(45,66,510,20,'サフィックス先頭順 / CALL  日時  MODE  得点  判定',9)
                    for n,i in enumerate(ordered[start:start+44]):
                        v=values[i];s=all_result.rows[i];cell(45,91+n*16,510,16,f"{v['call']}   {v['date']} {v['time']}   {v['mode']}   {s['points']}   {s.get('reason','')}",9)
    finally:p.end();buffer.close()
    return bytes(data),pages
