"""JARL R1/R2, Cabrillo and zLog CSV from contest working data."""
from dataclasses import dataclass
from datetime import datetime,timedelta
from decimal import Decimal,InvalidOperation
from pathlib import Path
import csv,io,json,re,unicodedata
from contest import entries
from contest_rules import score,matches,manual_score
from cabrillo_templates import validate as validate_template,BAND_MAP,ENUMS
from exporting import stamp
from model import validate_station
from storage import Snapshot,StorageError,ExternalChange,replace_bytes,operation_lock,VERSION

OATH='私は、JARL制定のコンテスト規約および電波法令にしたがい運用した結果、ここに提出するサマリーシートおよびログシートなどが事実と相違ないものであることを、私の名誉において誓います。'
ZLOG_HEADER=['Date','Time','TimeZone','CallSign','RSTSent','NrSent','RSTRcvd','NrRcvd','Serial','Mode','Band','Power','Multi1','Multi2','NewMulti1','NewMulti2','Points','Operator','Memo','CQ','Dupe','Reserve','TX','Power2','Reserve2','Reserve3','Freq','QsyViolation','PCName','Forced','QslState','Invalid','Area','RBN Verified']
ZLOG_BANDS={x:x for x in ('1.9','3.5','7','10','14','18','21','24','28','50','144','430','1200','2400','5600','10.1G','10.4G','24G','47G','77G','135G','248G')}
ZLOG_BANDS.update({'1.8':'1.9','3.8':'3.5','29':'28','433':'430','24000':'24G'})
ZLOG_MODES=('CW','SSB','FM','AM','RTTY','FT4','FT8','Other','DV')

def submission_band_sort_default(rule):
    return rule.get('event',{}).get('submission',{}).get('order')=='band_time'

def key(row):return str(row[2]),row[3]
def clean(value,label,required=False,ascii_only=False):
    if not isinstance(value,str):raise ValueError(label+'は文字列で指定してください。')
    value=unicodedata.normalize('NFKC',value).strip()
    if required and not value:raise ValueError(label+'を入力してください。')
    if any(ord(c)<32 or ord(c)==127 for c in value) or '<' in value or '>' in value:raise ValueError(label+'には改行・制御文字・<・>を使用できません。')
    if ascii_only and any(ord(c)>126 for c in value):raise ValueError(label+'は半角英数字・記号で入力してください。')
    return value

def check_jarl_official_required(format,info):
    """Validate fields the official JARL summary-maker marks as required.

    This is intentionally used by the interactive submission UI rather than
    the low-level writer so historical R1.0 files that omitted newer/stricter
    fields can still be reopened and inspected.  Values generated by PSLog
    itself (QSO totals / total score / FD coefficient) are validated by the
    scoring/export pipeline.
    """
    if format not in ('JARL R1.0','JARL R2.1'):
        return
    labels=(
        ('contest','コンテスト名'),('category','部門コード'),
        ('callsign','提出コールサイン'),('address','連絡先住所'),
        ('name','氏名・クラブ局名称'),('power','最大空中線電力'),
        ('email','メールアドレス'),
        ('date','宣誓日'),('signature','署名'),
    )
    for field,label in labels:
        clean(info.get(field,''),label,True)
    if info.get('oath') is not True:
        raise ValueError('宣誓内容を確認してチェックしてください。')
    if format=='JARL R1.0':
        clean(info.get('licenseclass',''),'従事者資格',True)
        powertype=clean(info.get('powertype',''),'出力の記載区分',True)
        if powertype not in ('定格出力','実測出力'):
            raise ValueError('出力の記載区分は「定格出力」または「実測出力」を選択してください。')
    elif info.get('fd') is True:
        clean(info.get('powersupply',''),'使用電源',True)

def token(value,label,required=True):
    v=clean(value,label,required,True)
    if any(c.isspace() for c in v):raise ValueError(label+'の途中に空白は入れられません。')
    return v

def numeric(value):
    s=format(Decimal(str(value)),'f')
    return s.rstrip('0').rstrip('.') if '.' in s else s

def integer(value,label):
    try:v=Decimal(str(value))
    except InvalidOperation:raise ValueError(label+'は整数である必要があります。')
    if not v.is_finite() or v!=v.to_integral_value() or v<0:raise ValueError(label+'は0以上の整数である必要があります。')
    return str(int(v))

def encoded(text,encoding):
    try:return (text+'\r\n').encode(encoding)
    except UnicodeEncodeError as e:raise ValueError('選択した文字コードで出力できない文字があります: '+repr(e.object[e.start:e.end])) from e

def check(selection,rule,draft,context=None):
    if not selection.rows:raise ValueError('対象交信がありません。')
    for session in selection.sessions:session.snapshot.check(session.path)
    own=selection.rows[0][0]
    if rule.get('id')!='iburi_hidaka' and any(r[0]!=own for r in selection.rows):raise ValueError('複数の自局運用を混在して出力できません。')
    for i,r in enumerate(selection.rows):
        if draft.get(key(r),{}).get('status')=='候補・要確認':raise ValueError(f'{i+1}行目の抽出候補を確認してください。')
    work_entries=entries(selection,draft);result=manual_score(work_entries) if rule.get('id')=='manual_other' else score(rule,work_entries,context)
    if result.problems:raise ValueError('採点が未確定です。\n'+'\n'.join(result.problems[:5]))
    return own,result

@dataclass
class ContestPlan:
    sessions:list
    guards:list
    data:bytes
    filename:str
    encoding:str
    qsos:int
    warnings:list
    def preview(self):return f'記入済みPDF / {self.qsos}交信 / {self.filename}\n保存後にPDFを開いて指定様式・参加帯の赤枠を確認してください。' if self.encoding=='binary' else self.data.decode(self.encoding)

def plan(selection,rule,draft,format,info,template=None,guards=(),context=None):
    from contest_calendar import working_rule
    rule=working_rule(rule,context)
    if (context or {}).get('submission_mode')=='checklog':
        if rule.get('schema')!=2 or 'event' not in rule:raise ValueError('全体チェックログは大会条件付きルールで指定してください。')
        if info.get('fd'):raise ValueError('全体チェックログではFDの得点係数を申告しません。FD欄を解除してください。')
    if any(type(d.get('checklog',False)) is not bool for d in draft.values()):raise ValueError('チェックログ指定は真偽値です。')
    from contest_submission_scope import select as select_submission
    source_count=len(selection.rows);selection=select_submission(selection,rule,draft,context or {})
    own,result=check(selection,rule,draft,context)
    if (format.startswith('JARL') or format=='所定様式PDF') and 'callsign' in info:
        own=validate_station(clean(info.get('callsign',''),'提出コールサイン',True),'')
    from contest_awards import submission_info
    if info.get('award_requests') and not format.startswith('JARL'):raise ValueError('大会内アワード申請はJARLサマリーへ記載してください。')
    info=submission_info(rule,entries(selection,draft),context or {},info)
    from contest_participation import submission_info as participation_info
    info=participation_info(rule,context or {},info,own)
    from contest_qualification import submission_comments
    info=submission_comments(rule,context or {},info)
    from contest_regional import submission_info as regional_info
    info=regional_info(rule,context or {},info,entries(selection,draft))
    if "event" in rule:
        from contest_regional_extended import submission_info as extended_info
        info=extended_info(rule,context or {},info,entries(selection,draft))
    from contest_cq import submission_info as cq_info
    info=cq_info(rule,context or {},info)
    from contest_last6 import submission_info as last_info
    info=last_info(rule,context or {},info)
    from contest_final9 import submission_info as final_info
    info=final_info(rule,context or {},info)
    from contest_remaining9 import submission_info as next_info
    info=next_info(rule,context or {},info,entries(selection,draft))
    from contest_newcomer import submission_info as newcomer_info
    info=newcomer_info(rule,context or {},info)
    if rule.get('event',{}).get('exchange',{}).get('kind')=='tagged_region' and (context or {}).get('submission_mode')!='checklog':
        from contest_event import prepare
        from contest_tagged_region import submission_comments as tag_comments
        rows,_,_=prepare(rule,entries(selection,draft),context)
        info=tag_comments(rule['event']['exchange'],rows,info)
    from contest_international import profile as international_profile
    international=international_profile(rule) and format=='Cabrillo'
    if any(d.get('checklog') for d in draft.values()) and (rule.get('schema')!=2 or 'event' not in rule or not format.startswith('JARL') and not international and format!='所定様式PDF'):
        raise ValueError('明示チェックログの出力は大会条件付きルールのJARL形式で対応しています。')
    if rule.get('event',{}).get('normalization') and not format.startswith('JARL') and not international and format!='所定様式PDF':
        raise ValueError('大会別表記変換の提出接続は現在JARL形式のみです。')
    whole=(context or {}).get('submission_mode')=='checklog'
    if whole and not format.startswith('JARL') and not international and format!='所定様式PDF':raise ValueError('全体チェックログはJARL形式で出力してください。')
    category=next((c for c in rule.get('event',{}).get('categories',[]) if c['id']==(context or {}).get('category')), {})
    tx_ids=[] if whole else category.get('timing',{}).get('band_change',{}).get('tx_ids',[])
    if tx_ids and format.startswith('JARL'):
        from contest_jarl import jarl_tx_ids
        tx_ids=jarl_tx_ids(rule,category)
    if tx_ids and format=='Cabrillo' and not any(c.get('source')=='tx' for c in (template or {}).get('columns',[])):
        raise ValueError('この部門は送信系列の出力が必要です。TX列を持つCabrilloテンプレートを選択してください。')
    submit=rule.get('event',{}).get('submission')
    if submit and format not in submit['formats']:raise ValueError('この大会では選択した提出形式に対応していません。')
    if submit and format.startswith('JARL'):
        from contest_qualification import qualification_submission
        from contest_station import check_submission
        check_submission(rule,context or {},info,own)
        if not whole:qualification_submission(category,context or {},info,format)
        from contest_club import submission_info as club_info
        info=club_info(submit.get('club_entry'),context or {},info)
        labels=dict(email='メールアドレス',opplace='運用地',multioplist='運用者一覧',licensedate='免許年月日',age='年齢')
        for field in submit.get('required_fields',[]):
            if not clean(info.get(field,''),field):raise ValueError('この大会の提出には'+labels[field]+'が必要です。')
        category={} if whole else next(c for c in rule['event']['categories'] if c['id']==context['category'])
        from contest_locations import check as check_location,location
        expected_location=check_location(rule['event'],category,context or {})
        if expected_location and location(info.get('opplace',''))!=expected_location:raise ValueError('提出運用地と部門の運用地が一致しません。')
        if category.get('operator')=='MO' and (info.get('multiop') is not True or not str(info.get('multioplist','')).strip()):raise ValueError('マルチオペ部門には運用者一覧が必要です。')
        if category.get('operator')=='SO' and info.get('multiop'):raise ValueError('シングルオペ部門と提出者設定が一致しません。')
        if info.get('zone','JST') not in submit.get('allowed_zones',[submit['zone']]):raise ValueError('規約指定のログ時刻と異なります。')
        if info.get('contest')!=submit['contest']:raise ValueError('大会名が採点ルールと一致しません。')
        if Decimal(str(info.get('power','0')))!=Decimal(str((context or {}).get('power',0))):raise ValueError('提出電力が参加条件で確認した値と異なります。')
    if 'event' in rule and format.startswith('JARL') and info.get('category')!=(rule['event'].get('regional',{}).get('checklog_code','CHECKLOG') if whole else category.get('submission_code',(context or {}).get('category'))):
        raise ValueError('提出部門コードが採点時の参加部門と異なります。')
    if format in ('JARL R1.0','JARL R2.1'):data=jarl(selection,rule,draft,result,info,format[-4:],tx_ids,own);ext='txt';encoding='cp932';warnings=[]
    elif format=='所定様式PDF':
        if rule.get('id')!='toyama_emergency':raise ValueError('この大会の所定PDF様式は未対応です。')
        from contest_toyama_pdf import render
        templates=[Path(__file__).parent/'config/templates/pdf'/('toyama_'+n+'.pdf') for n in ('OSOSUMMARY','QSOLOG')]
        guards=list(guards)+[(p,Snapshot.read(p)) for p in templates]
        data,pages=render(selection,rule,draft,result,info,context);ext='pdf';encoding='binary';warnings=[f'記入済み支部様式 {pages}ページ。保存したPDFを開いて確認してください。']
    elif format=='Cabrillo':
        if international:
            from contest_international import export_values
            selection,draft=export_values(selection,rule,draft,info,template,context or {})
        data,warnings=cabrillo(selection,draft,result,info,template);ext='log';encoding=template['encoding']
    elif format=='zLog令和版CSV':data,warnings=zlog(selection,rule,draft,result,info);ext='csv';encoding='utf-8-sig'
    else:raise ValueError('未対応の提出形式です。')
    if source_count!=len(selection.rows):warnings.append(f'提出部門の日時・バンド・モードに属さない{source_count-len(selection.rows)}行を提出用表示から除外しました。元ログは変更していません。')
    if rule.get('id')=='miyazaki' and len(data)>1000000:raise ValueError('宮崎の提出本文は1MB以下です。')
    warnings.extend(getattr(result,'timing_summary',[]))
    filename=own.replace('/','-')+('_'+str(info.get('category','')).replace('/','-') if rule.get('event',{}).get('regional',{}).get('entry_set') else '')+'.'+ext
    if rule.get('id')=='shizuoka':filename=own.replace('/','_')+'.txt'
    if rule.get('id')=='all_hyogo' and info.get('_hyogo_second'):filename=public_filename=own.split('/')[0]+'-2'+('\u005f'+own.split('/',1)[1].replace('/','_') if '/' in own else '')+'.txt'
    return ContestPlan(list(selection.sessions),list(guards),data,filename,encoding,len(selection.rows),warnings)

def jarl(selection,rule,draft,result,info,version,tx_ids=(),own_call=None):
    own=own_call or selection.rows[0][0];values={}
    for name in ('contest','category','name','address','power','signature','date'):values[name]=clean(info.get(name,''),name,True)
    if info.get('oath') is not True:raise ValueError('宣誓文を確認してチェックしてください。')
    try:
        power=Decimal(values['power'])
        if not power.is_finite() or not 0<=power<=100000000:raise ValueError()
        date=datetime.strptime(values['date'],'%Y-%m-%d')
    except (ValueError,InvalidOperation):raise ValueError('最大電力または宣誓日が不正です。')
    zone=info.get('zone','JST')
    if zone not in ('JST','UTC'):raise ValueError('時刻基準を選択してください。')
    if info.get('fd') and rule['multi2']['kind']=='off' and rule.get('event',{}).get('station_factor')!='jarl_fd':raise ValueError('FDの局種係数を段階4の第二マルチで設定してください。')
    if info.get('fd') and rule.get('event',{}).get('station_factor')!='jarl_fd':
        for f in ('opplace','powersupply'):
            if not clean(info.get(f,''),f):raise ValueError('FDでは運用地・使用電源を入力してください（同住所・商用電源も記載できます）。')
    if info.get('multiop') and not clean(info.get('multioplist',''),'運用者一覧'):raise ValueError('マルチオペの運用者一覧を入力してください。')
    from clubs import number as club_number
    club=club_number(info.get('clubnumber',''),optional=True)
    def tag(name,value):return f'<{name}>{value}</{name}>'
    lines=[f'<SUMMARYSHEET VERSION={version}>',tag('CONTESTNAME',values['contest']),tag('CATEGORYCODE',clean(values['category'],'部門コード',True))]
    if version=='R1.0':lines.append(tag('CATEGORYNAME',clean(info.get('categoryname',''),'部門名称')))
    public_call=validate_station(own,'')
    if rule.get('id')=='all_hyogo' and info.get('_hyogo_second'):
        parts=public_call.split('/');parts[0]+='-2';public_call='/'.join(parts)
    lines.append(tag('CALLSIGN',public_call))
    optional=[('opcall','OPCALLSIGN'),('tel','TEL'),('email','EMAIL'),('opplace','OPPLACE'),('powersupply','POWERSUPPLY'),('comments','COMMENTS'),('multioplist','MULTIOPLIST')]
    if version=='R1.0':
        optional += [('licenseclass','LICENSECLASS'),('powertype','POWERTYPE'),('equipment','EQUIPMENT'),('clubname','REGCLUBNAME')]
    else:optional += [('licensedate','LICENSEDATE'),('age','AGE')]
    if version=='R1.0' and rule.get('id')=='jarl_world_wide_rtty':optional.append(('age','AGE'))
    from contest_normalization import working_values as normalize
    normalized=[normalize(rule.get('event',{}),row[1].band,row[1].mode,draft.get(key(row),{}).get('contest_band','')) for row in selection.rows]
    band_order={b:i for i,b in enumerate(dict.fromkeys(b for w in rule.get('event',{}).get('windows',[]) for b in w['bands']))}
    rule_band_sort=submission_band_sort_default(rule)
    requested_band_sort=info.get('sort_band_time',rule_band_sort)
    if type(requested_band_sort) is not bool:raise ValueError('ログのバンド順設定が不正です。')
    band_sort=requested_band_sort
    def band_key(band):
        if band in band_order:return (0,band_order[band],0,'')
        text=str(band).strip().upper();scale=1000 if text.endswith(('GHZ','G')) else 1
        numeric_text=text[:-3] if text.endswith('GHZ') else text[:-1] if text.endswith('G') else text[:-3] if text.endswith('MHZ') else text
        try:return (1,0,float(numeric_text)*scale,text)
        except ValueError:return (2,0,0,text)
    band_labels=rule.get('event',{}).get('submission',{}).get('band_labels',{})
    regional_checklog=rule.get('event',{}).get('regional',{}).get('outside_category_checklog',False)
    summary_mask=[not (regional_checklog and x.get('reason')=='参加部門のバンド・モード対象外') for x in result.rows]
    if version=='R1.0':
        summary_bands=list(dict.fromkeys(b for b,m in normalized))
        if band_sort:summary_bands.sort(key=band_key)
        for band in summary_bands:
            indexes=[i for i,(b,m) in enumerate(normalized) if b==band and summary_mask[i]];pts=sum(result.rows[i]['points'] for i in indexes);multi=len({result.rows[i]['multi'] for i in indexes if result.rows[i]['multi'] is not None})
            if rule.get('event',{}).get('regional',{}).get('profile')=='kyoto':multi=len({tuple(token) for i in indexes for token in result.rows[i].get('multiplier_tokens',[])})
            if rule.get('event',{}).get('regional',{}).get('profile')=='nara':multi=len({tuple(token) for i in indexes for token in result.rows[i].get('multiplier_tokens',[]) if token[0]=='tail'})
            output_band=band_labels.get(band,band)
            label=token(output_band,'バンド')+('' if output_band.endswith(('G','GHz','MHz')) else 'MHz');lines.append(f'<SCORE BAND={label}>{len(indexes)},{numeric(pts)},{multi}</SCORE>')
        lines.append(f'<SCORE BAND=TOTAL>{sum(summary_mask)},{numeric(result.points)},{result.multi1 if rule["schema"]==2 or rule["multi1"]["kind"]!="off" else 0}</SCORE>')
    lines.extend([tag('TOTALSCORE',getattr(result,'ajd_completion','') or numeric(result.total)),tag('ADDRESS',values['address']),tag('NAME',values['name']),tag('POWER',numeric(power))])
    if info.get('fd'):lines.append(tag('FDCOEFF',numeric(result.multi2)))
    for field,tagname in optional:
        value=clean(info.get(field,''),field)
        if value:
            if field=='licensedate':
                try:datetime.strptime(value,'%Y-%m-%d')
                except ValueError:raise ValueError('免許年月日はYYYY-MM-DDです。')
            if field=='age' and not (rule.get('id')=='jarl_world_wide_rtty' and value=='YOUTH'):value=integer(value,'年齢')
            lines.append(tag(tagname,value))
    if club:lines.append(tag('REGCLUBNUMBER',club))
    lines.extend([tag('OATH',OATH),tag('DATE',date.strftime('%Y年%m月%d日')),tag('SIGNATURE',values['signature']),'</SUMMARYSHEET>','<LOGSHEET TYPE="PSLog">',f'DATE ({zone}) TIME BAND MODE CALLSIGN SENTNo RCVDNo Mlt Pts'])
    if rule.get('event',{}).get('regional',{}).get('profile')=='ja0_serial':lines[-1]=f'DATE ({zone}) TIME CALLSIGN SENTNo RCVDNo Mlt BAND MODE Pts'
    seen=set()
    nara=rule.get('event',{}).get('regional',{}).get('profile')=='nara'
    if rule.get('id') in ('miyazaki','all_hyogo','kcwa_cw','shizuoka','hiroshima_was'):lines[-1]=f'DATE ({zone}) TIME BAND MODE CALLSIGN SENTNo RCVNo MULTI PTS'
    if nara:lines[-1]=f'DATE ({zone}) TIME BAND MODE CALLSIGN SENTNo RCVNo Multi1 Multi2 PTS'+(' Op.' if info.get('multiop') else '')
    if rule.get('id')=='iburi_hidaka':lines[-1]+=' MYCALL'
    if tx_ids:lines[-1]+=' TX'
    indices=list(range(len(selection.rows)))
    if band_sort:
        indices.sort(key=lambda i:(band_key(normalized[i][0]),stamp(selection.rows[i][1]),i))
    for i in indices:
        row=selection.rows[i]
        _,q,_,_=row;d=draft.get(key(row),{});dt=stamp(q)-(timedelta(hours=9) if zone=='UTC' else timedelta());s=result.rows[i];m='/'.join(s['multiplier_values']) if s.get('multiplier_values') else s['multi'];mk=(normalized[i][0] if rule['multi1']['per_band'] else '',m);show=m.replace(' / ','/') if m is not None and mk not in seen else '-';seen.add(mk)
        fields=[dt.strftime('%Y-%m-%d'),dt.strftime('%H:%M'),token(normalized[i][0],'バンド'),token(normalized[i][1],'モード'),validate_station(q.call,''),token(d.get('rst_sent',q.sent),'送信RST'),(clean(d.get('sent',''),'送信名',True) if rule.get('id')=='qso_party' else token(d.get('sent',''),'送信番号',required=rule.get('id') not in ('miyazaki','all_hyogo'))),token(d.get('rst_received',q.received),'受信RST'),(clean(d.get('received',''),'受信名',True) if rule.get('id')=='qso_party' else token(d.get('received',''),'受信番号',required=rule.get('id') not in ('miyazaki','all_hyogo'))),token(str(show),'マルチ'),numeric(s['points'])]
        fields[2]=band_labels.get(normalized[i][0],fields[2])
        if rule.get('event',{}).get('exchange',{}).get('kind') in ('jarl_region_power','jarl_band_power') and fields[3].upper() in ('USB','LSB'):fields[3]='SSB'
        if tx_ids:
            tx=token(d.get('tx',''),'送信波系列')
            if tx not in tx_ids:raise ValueError(f'{i+1}行目の送信波系列を確認してください。対象外・重複行も系列を省略できません。')
            fields.append(tx)
            if fields[3].upper() in ('USB','LSB'):fields[3]='SSB'
        if rule.get('event',{}).get('regional',{}).get('profile')=='ja0_serial':fields=[fields[0],fields[1],fields[4],fields[5]+fields[6],fields[7]+fields[8],fields[9],fields[2],fields[3],fields[10]]
        elif rule.get('id') in ('kcj','kcj-topband','miyazaki','all_hyogo','kcwa_cw','shizuoka','hiroshima_was'):fields=fields[:5]+[fields[5]+fields[6],fields[7]+fields[8]]+fields[9:]
        if nara:
            from contest_regional import base_call
            valid=s.get('eligible') or s.get('reason')=='重複'
            fields=fields[:5]+[fields[5]+fields[6],fields[7]+fields[8],base_call(q.call)[-1] if valid else '-',fields[8][:2] if valid else '-',fields[10]]
            if info.get('multiop'):fields.append(token(d.get('operator_name',''),'実運用者'))
        if rule.get('id')=='iburi_hidaka':fields.append(validate_station(row[0],''))
        lines.append(('X ' if rule.get('id')!='shizuoka' and (d.get('checklog') or regional_checklog and s.get('reason')=='参加部門のバンド・モード対象外') and info.get('category')!=rule.get('event',{}).get('regional',{}).get('checklog_code','CHECKLOG') else '')+('\t' if rule.get('id')=='qso_party' else ' ').join(fields))
    lines.append('</LOGSHEET>');return encoded('\r\n'.join(lines),'cp932')

def cabrillo(selection,draft,result,info,t):
    if t is None:raise ValueError('出力テンプレートを選択してください。')
    validate_template(t);own=validate_station(selection.rows[0][0],'');contest=clean(info.get('CONTEST',t['contest']),'CONTEST',True,True)
    if not re.fullmatch('[A-Z0-9-]{1,32}',contest):raise ValueError('CONTESTは大文字英数字と-、32文字までです。')
    lines=['START-OF-LOG: '+t['version'],'CREATED-BY: PSLog '+VERSION,'CALLSIGN: '+own,'CONTEST: '+contest];headers={}
    if not (t.get('rule_id')=='ww-digi' and getattr(result,'unscored_submission',False) and result.total is None):lines.append('CLAIMED-SCORE: '+integer(result.total,'総得点'))
    for h in t['headers']:
        tag=h['tag'];value=info.get(tag,h['default']);multi=tag in ('ADDRESS','SOAPBOX','OPERATORS')
        if not isinstance(value,str):raise ValueError(tag+'は文字列です。')
        parts=value.splitlines() if multi else [value]
        parts=[clean(p,tag,False,t['encoding']=='ascii') for p in parts if p.strip()]
        if h['required'] and not parts:raise ValueError(tag+'を入力してください。')
        if tag=='ADDRESS' and len(parts)>6:raise ValueError('ADDRESSは6行以内です。')
        for p in parts:
            if h['choices'] and p not in h['choices']:raise ValueError(tag+'がテンプレートの候補にありません。')
            if tag in ENUMS and p not in ENUMS[tag]:raise ValueError(tag+'が標準値ではありません。')
            limit=45 if tag=='ADDRESS' else 75 if tag in ('NAME','SOAPBOX') else 64 if tag=='OPERATORS' else None
            if limit is not None and len(p)>limit:raise ValueError(tag+f'は1行{limit}文字以内です。')
            lines.append(tag+': '+p)
        headers[tag]=' '.join(parts)
    if headers.get('CATEGORY-OPERATOR')=='MULTI-OP' and (not headers.get('CATEGORY-TRANSMITTER') or not headers.get('OPERATORS')):raise ValueError('MULTI-OPには送信機区分とOPERATORSが必要です。')
    warnings=[];used_band=False
    if t.get('rule_id')=='jarl_world_wide_rtty':warnings.append('CONTEST等の未指定ヘッダーは暫定です。提出フォームで最終確認してください。周波数は規約で許容されたMHz帯域表示です。')
    for i,row in enumerate(selection.rows):
        _,q,_,_=row;d=draft.get(key(row),{});dt=stamp(q)-timedelta(hours=9);mode=q.mode.strip().upper();mapped=t['modes'].get(mode)
        if mapped is None:
            for base in ('FT8','FT4','FT2','FREEDV'):
                if base in mode and base in t['modes']:mapped=t['modes'][base];break
        if mapped is None:raise ValueError(f'{i+1}行目のMODE対応がありません: '+q.mode)
        freq=clean(d.get('frequency',''),'周波数',False,True)
        vhf=q.band in ('50','144','430','433','1200','2400','5600','10000','24000')
        if t.get('rule_id')=='jarl_world_wide_rtty':freq=q.band
        elif vhf:freq=BAND_MAP[q.band]
        elif not freq:
            if t['frequency']=='actual':raise ValueError(f'{i+1}行目の実周波数（kHz）を補完してください。')
            freq=BAND_MAP.get(q.band)
            if not freq:raise ValueError('Cabrilloのバンド対応がありません: '+q.band)
            used_band=True
        elif not vhf:
            try:
                f=Decimal(freq)
                if not f.is_finite() or f<=0 or f!=f.to_integral_value():raise ValueError()
            except (InvalidOperation,ValueError):raise ValueError('実周波数はkHzの正の整数です。')
            freq=str(int(f))
        values={'frequency':freq,'mode':mapped,'date':dt.strftime('%Y-%m-%d'),'time':dt.strftime('%H%M'),'own':own,'call':validate_station(q.call,''),'rst_sent':d.get('rst_sent',q.sent),'rst_received':d.get('rst_received',q.received),'sent':d.get('sent',''),'received':d.get('received',''),'my_grid':d.get('my_grid',''),'his_grid':d.get('his_grid',''),'tx':d.get('tx','')};cols=[]
        for c in t['columns']:
            v=clean(c['literal'] if c['source']=='literal' else values[c['source']],f"{i+1}行目 {c['source']}",True,True)
            if c['source']=='tx' and v not in (tuple('012345') if t.get('rule_id','').startswith('all_asian_dx_') else ('0','1')):raise ValueError('送信機番号は0または1です。')
            if c['source'] in ('my_grid','his_grid') and not (t.get('rule_id')=='ww-digi' and c['source']=='his_grid' and v=='ZZ00') and not re.fullmatch('[A-Ra-r]{2}[0-9]{2}(?:[A-Xa-x]{2})?',v):raise ValueError('GLは4または6文字です。')
            if c['part']:
                parts=v.split()
                if c['part']>len(parts):raise ValueError(f'{i+1}行目のナンバー部分が不足しています。')
                v=parts[c['part']-1]
            if len(v)>c['width']:raise ValueError(f"{i+1}行目 {c['source']} が幅{c['width']}を超えています: {v}")
            cols.append(v.ljust(c['width']) if c['align']=='left' else v.rjust(c['width']))
        lines.append(('X-QSO: ' if d.get('checklog') else 'QSO: ')+' '.join(cols))
    if used_band:warnings.append('実周波数が空欄の交信は、テンプレート設定に従いバンド識別値を出力しました。')
    lines.append('END-OF-LOG:');return encoded('\r\n'.join(lines),t['encoding']),warnings

def zlog(selection,rule,draft,result,info):
    zone=info.get('zone','JST');power=info.get('power_code','')
    if zone not in ('JST','UTC') or not info.get('split_power',False) and power not in ('P','L','M','H'):raise ValueError('zLogの時刻基準と電力コードを指定してください。')
    out=io.StringIO(newline='');writer=csv.writer(out,lineterminator='\r\n',quoting=csv.QUOTE_ALL);writer.writerow(ZLOG_HEADER);seen=set();warnings=[]
    for i,row in enumerate(selection.rows):
        _,q,_,_=row;d=draft.get(key(row),{});s=result.rows[i];band=ZLOG_BANDS.get(q.band)
        if band is None:raise ValueError('zLogに正確に対応しないBANDです: '+q.band)
        mode=q.mode.strip()
        if mode not in ZLOG_MODES:raise ValueError('zLogに正確に対応しないMODEです: '+mode)
        def rst(v):
            v=token(v,'RST')
            if not re.fullmatch('[+-]?[0-9]+',v) or not -2147483648<=int(v)<=2147483647:raise ValueError('zLogのRSTは整数に変換できる必要があります。')
            return str(int(v))
        sent=token(d.get('sent',''),'送信番号');row_power=power
        if info.get('split_power',False):
            if len(sent)<2 or sent[-1] not in ('P','L','M','H'):raise ValueError('電力コード分離には送信番号末尾のP/L/M/Hが必要です。')
            row_power=sent[-1];sent=sent[:-1]
        dt=stamp(q)-(timedelta(hours=9) if zone=='UTC' else timedelta());multi=s['multi'] or '';mk=(band if rule['multi1']['per_band'] else '',multi);new=bool(multi) and mk not in seen;seen.add(mk);memo=q.remarks if info.get('memo',True) else ''
        if '\\n' in memo:raise ValueError('RMKSに文字列 \\n があり、zLogが改行として切り詰めます。メモ引継ぎをOFFにしてください。')
        if not isinstance(memo,str) or any(ord(c)<32 for c in memo):raise ValueError('RMKSに制御文字があります。')
        tx=d.get('tx','') or '0'
        if tx not in ('0','1'):raise ValueError('TXは0または1です。')
        freq=clean(d.get('frequency',''),'周波数')
        if freq:
            try:hz=Decimal(freq)
            except InvalidOperation:raise ValueError('周波数が不正です。')
            if not hz.is_finite() or hz<=0:raise ValueError('周波数が不正です。')
            freq=format(hz,'f')
        fields=[dt.strftime('%Y/%m/%d'),dt.strftime('%H:%M:%S'),zone,validate_station(q.call,''),rst(d.get('rst_sent',q.sent)),sent,rst(d.get('rst_received',q.received)),token(d.get('received',''),'受信番号'),str(i+1),mode,band,row_power,multi,'',str(new), 'False',integer(s['points'],'交信得点'),clean(info.get('operator',''),'運用者'),memo,'False',str(s['reason']=='重複'),'0',tx,'0','0','0',freq,'False','','False','0','False','','False']
        if len(fields)!=34:raise AssertionError('zLog column count')
        writer.writerow(fields)
    if not info.get('split_power',False):warnings.append('送信番号は全文をNrSentへ出力します。zLog定義で $P を追加する場合は電力コード分離を選択してください。')
    warnings.append('zLog側で対象コンテストと自局を設定し、再計算してください。第二マルチ・地域・QSL等の専用フラグは未設定です。')
    return out.getvalue().encode('utf-8-sig'),warnings

def save(plan,directory):
    directory=Path(directory).resolve()
    if not directory.is_dir():raise ValueError('存在する保存先フォルダーを指定してください。')
    for session in plan.sessions:session.snapshot.check(session.path)
    for path,snapshot in plan.guards:snapshot.check(Path(path))
    base=Path(plan.filename)
    for i in range(10000):
        path=directory/(base.stem+('' if i==0 else f'_{i:03d}')+base.suffix)
        if path.exists():continue
        try:replace_bytes(path,plan.data,Snapshot(None,None))
        except ExternalChange:continue
        return path
    raise StorageError('空いている出力ファイル名を確保できません。')

class SubmitProfiles:
    """Separate config avoids racing the main window's in-memory preferences."""
    KEYS={'jarl':('name','address','power','signature','clubnumber','clubname'),'cabrillo':('NAME','ADDRESS','ADDRESS-CITY','ADDRESS-STATE-PROVINCE','ADDRESS-POSTALCODE','ADDRESS-COUNTRY')}
    def __init__(self,root):
        self.path=Path(root)/'config'/'contest_submit.cfg';self.snapshot=Snapshot.read(self.path)
        try:self.values=json.loads(self.snapshot.data.decode('utf-8')) if self.snapshot.data else {}
        except (ValueError,UnicodeError) as e:raise StorageError('提出者設定を読み込めません。') from e
        if not isinstance(self.values,dict):raise StorageError('提出者設定が不正です。')
        for k in self.KEYS:
            if k in self.values and (not isinstance(self.values[k],dict) or any(not isinstance(v,str) for v in self.values[k].values())):raise StorageError('提出者設定が不正です。')
    def remember(self,kind,info):
        values=dict(self.values);previous=dict(values.get(kind,{}) if isinstance(values.get(kind,{}),dict) else {})
        values[kind]={k:(info[k] if k in info else previous.get(k,'')) for k in self.KEYS.get(kind,())};self.path.parent.mkdir(parents=True,exist_ok=True)
        with operation_lock(self.path.parent):replace_bytes(self.path,json.dumps(values,ensure_ascii=False,indent=2).encode(),self.snapshot)
        self.values=values;self.snapshot=Snapshot.read(self.path)
